### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by maslihov-vlad** [b-fg/nuatsbot#13]
Hello, I've got such an error. Don't know how to fix)
from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

  warnings.warn(
Traceback (most recent call last):
  File "c:/Users/Admin/Desktop/nuatsbot-master/nuatsbot-master/nuats_bot.py", line 124, in <module>
    main()
  File "c:/Users/Admin/Desktop/nuatsbot-master/nuatsbot-master/nuats_bot.py", line 112, in main
    tickers_TA_list =  list(tqdm(executor.map(TA_task, a), total=len(a)))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 434, in result
    self._condition.wait(timeout)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\threading.py", line 302, in wait
    waiter.acquire()

**Comment by b-fg** [comment]
Your error seems to be related to what you are doing with `sklearn.pipeline import make_pipeline` and this is not part of the nuatsbot source code. The other stuff in the message is just a warning, not an error.

**Comment by b-fg** [comment]
Closing due to inactivity.
