### ISSUE TITLE
Good way to keep bot from timing out

### ISSUE THREAD

**Issue by aolin480** [b-fg/nuatsbot#5]
After running for only a short while, the app crashes due to a timeout reaching binance api. Here's the output when the app stops:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x120b78d68>, 'Connection to api.binance.com timed out. (connect timeout=10)')
```

**Comment by b-fg** [comment]
A time out can occur for multiple reasons. Please provide and example of your configuration file and details to be able to reproduce the error.

**Comment by b-fg** [comment]
It might as well be a slow response from binance or that your network connection to the binance server is slow itself. I could add a try-catch to deal with this exception if that helps.

**Comment by aolin480** [comment]
Yeah, I tried upping the timeout in the binance client, but it's still dropping the app in some cases. A try catch may be a good way to rectify that

**Comment by b-fg** [comment]
Closing this for lack of information. If you want to reopen please provide a detailed way to reproduce the error so I can fix it. Thanks!
